// User-facing strings live here (ADR 0004). Replace with @vscode/l10n bundles when a second
// locale is added; call sites keep using t().
const en = {
  "session.taskPlaceholder": "Describe a task for catherd…",
  "session.roleGuide":
    "catherd plans the work, sends each part to the right role and model, and reports back. Ask for a researcher or reviewer in your task to steer it.",
  "session.start": "Start task",
  "session.resume": "Resume saved run",
  "session.interrupt": "Interrupt",
  "session.jumpLatest": "Latest",
  "session.stop": "Stop session",
  "session.new": "New chat",
  "session.newConfirm": "Stop and start new?",
  "session.followUp": "Message the orchestrator…",
  "session.send": "Send",
  "session.attach": "Attach files",
  "session.dropHere": "Drop files to attach",
  "session.removeAttachment": "Remove {name}",
  "session.attachments": "Attached files",
  "session.attachTooLarge":
    "{name} can't be attached: drop it from the VS Code Explorer (hold Shift) or use Attach files so its path is sent instead.",
  "session.pendingPrompts": "Pending requests from the orchestrator",
  "session.transcript": "Session transcript",
  "session.you": "You",
  "session.orchestrator": "catherd",
  "session.steps": "{n} steps",
  "session.stepsRunning": "{n} running",
  "session.showEarlier": "Show {n} earlier steps",
  "session.input": "Input",
  "session.output": "Output",
  "session.runStartedTitle": "Run started",
  "session.turnDone": "Turn complete",
  "session.turnFailed": "Turn ended: {subtype}",
  "settings.open": "CatHouse settings",
  "settings.title": "Settings",
  "settings.fontSize": "Text size",
  "settings.smaller": "Smaller text",
  "settings.larger": "Larger text",
  "settings.presets": "Text size presets",
  "settings.fontSizeHelp": "Scales CatHouse relative to your VS Code font size.",
  "settings.preview": "The quick brown fox · Aa 123",
  "settings.apply": "Apply",
  "settings.cancel": "Cancel",
  "workspace.repo": "Repository for this chat",
  "workspace.none": "No repository selected",
  "workspace.add": "Add folders…",
  "workspace.removeNamed": "Remove {name} from workspace",
  "workspace.removeConfirm": "Remove from workspace?",
  "workspace.required": "Choose or add a repository before starting a task.",
  "runs.continue": "Continue in chat",
  "runs.continueHelp":
    "Resume this repo's saved orchestrator session (or start one that resumes the latest run).",
  "session.mode": "Permissions",
  "session.modeHelp":
    "catherd's own tools are always allowed; this sets how other tool calls are handled.",
  "session.mode.default": "ask (your Claude settings)",
  "session.mode.acceptEdits": "auto-accept file edits",
  "session.mode.plan": "plan only",
  "session.mode.auto": "auto (classifier)",
  "session.inbound": "catherd reported back",
  "session.compacted":
    "The conversation was compacted. catherd runs can lose track of their protocol after this; check that routing, the reviewer and the verifier still run.",
  "tabs.setup": "Setup",
  "tabs.session": "Chat",
  "tabs.runs": "Runs",
  "tabs.profiles": "Profile",
  "tabs.models": "Models",
  "tabs.label": "CatHouse dashboard",
  "status.failed": "setup needs attention",
  "common.loading": "Loading…",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "time.secs": "{n}s ago",
  "time.mins": "{n} min ago",
  "time.hours": "{n} h ago",
  "time.days": "{n} d ago",
  "runs.live": "{n} live",
  "runs.roleRuns": "{n} role runs",
  "runs.landed": "{n} landed",
  "runs.budget": "budget {pct}%",
  "runs.session": "session {name}",
  "runs.sessionLive": "session {name} (live)",
  "runs.continuedIn": "continued in {name}",
  "runs.questionsTitle": "Parked questions",
  "runs.questionsHelp":
    "catherd parked these milestones for your answer; the other milestones go on. Answer in the orchestrator chat.",
  "runs.verifierStep": "Verifier: {item} ({ago})",
  "runs.verifierCarried": "Verifier: {item}, carried over ({ago})",
  "runs.corrupt": "{n} run folders could not be read (see Setup → Logs).",
  "runs.empty": "No runs yet. Start one from Chat.",
  "runs.back": "Runs",
  "runs.started": "started {ago}",
  "runs.budgetTitle": "Budget",
  "runs.jevLine": "Jev: {decisions} decisions, {fallbacks} fell back",
  "runs.liveTitle": "Live",
  "runs.cancelConfirm": "Click again to cancel",
  "runs.cancelled": "{name}: {status}",
  "runs.climbsTitle": "Climbs",
  "runs.environment": "(environment)",
  "runs.routesTitle": "Routes",
  "runs.noRoutes": "No lane has been routed yet.",
  "runs.landedTitle": "Landed",
  "runs.recordsTitle": "Role runs",
  "runs.noRecords": "No role has finished yet.",
  "runs.violations": "{n} files outside its lane",
  "runs.violationFiles": "Wrote outside its lane: {files}",
  "runs.tokensLine": "{input}k in / {output}k out tokens",
  "runs.changed": "changed {files}",
  "runs.debug": "Debug (exit, stderr, events)",
  "runs.noExit": "no exit.json",
  "runs.stateTitle": "state.md",
  "profiles.active": "active",
  "profiles.thisRepo": "this repo",
  "profiles.profile": "Profile",
  "profiles.help.routing":
    "Prefer lower cost or higher speed; Jev can refine routing from run history.",
  "profiles.help.billing": "Tell catherd which quota or billing pool each backend consumes.",
  "profiles.help.harness": "Isolated harnesses avoid loading your personal backend configuration.",
  "profiles.help.budget": "Soft caps guide the orchestrator; an empty value means no cap.",
  "profiles.help.failover": "Choose a stand-in from a different quota when a rung is unavailable.",
  "profiles.help.timeouts":
    "Limit idle and wall time, preflight confirmation and heavy-work slots.",
  "profiles.help.notify": "Choose which run events produce notifications.",
  "profiles.unbind": "Unbind this repo",
  "profiles.activated": "{name} is now the active profile.",
  "profiles.bound": "This repo now runs on {name}.",
  "profiles.unbound": "This repo runs on the active profile again.",
  "profiles.name": "Profile name",
  "profiles.create": "Create",
  "profiles.creating": "Creating…",
  "profiles.badName": "Profile names use lowercase letters, digits and dashes (max 32).",
  "profiles.exists": "A profile named {name} already exists.",
  "profiles.created": "Created {name}.",
  "profiles.deleteConfirm": "Click again to delete",
  "profiles.removed": "Deleted {name}.",
  "profiles.boundTo": "Bound to: {repos}",
  "profiles.undo": "Undo",
  "profiles.save": "Save…",
  "profiles.newSession": "Start a new orchestrator session to use: {agents}",
  "profiles.appliesWhen":
    "Applies to: native Claude agents in new sessions; codex, claude-code, opencode, cursor, grok and antigravity from the next dispatch.",
  "profiles.roles": "Roles",
  "profiles.access": "Access for {role}",
  "profiles.defaultRung": "start on",
  "profiles.cheapest": "the cheapest that clears the bar",
  "profiles.up": "Move up",
  "profiles.down": "Move down",
  "profiles.remove": "Remove",
  "profiles.addRung": "Add a rung to {role}",
  "profiles.unscored": "unscored: catherd infers its values",
  "profiles.treatPrompt":
    "{rung} is unscored. catherd will borrow its nearest stand-in's values; you can pick one:",
  "profiles.addWithTreat": "Add",
  "profiles.addInferred": "Add (let catherd infer)",
  "profiles.routing": "Routing",
  "profiles.objective": "Objective",
  "profiles.jev": "Jev",
  "profiles.billing": "Billing",
  "profiles.harness": "Harness isolation",
  "profiles.isolated": "isolated",
  "profiles.ownConfig": "your own config",
  "profiles.budget": "Budget (soft cap)",
  "profiles.noCap": "no cap",
  "profiles.failover": "Failover",
  "profiles.inferred": "inferred",
  "profiles.failoverFrom": "when this rung hits a limit…",
  "profiles.failoverTo": "…stand in with",
  "profiles.add": "Add",
  "profiles.timeouts": "Limits",
  "profiles.preflightConfirm": "Show preflight commands before running them",
  "profiles.heavy": "Heavy-work slots",
  "profiles.notify": "Notify me when",
  "profiles.summary.roles": "{n}/{total} enabled",
  "models.refresh": "Refresh catalog",
  "models.refreshing": "Refreshing model listings…",
  "models.count": "{n} models",
  "models.treated": "{rung} is now treated like {like}.",
  "models.role": "Role",
  "models.anyRole": "any role",
  "models.backend": "Backend",
  "models.anyBackend": "any backend",
  "models.search": "Search models",
  "models.scoredOnly": "scored only",
  "models.none": "No model matches.",
  "models.notListed": "not in your account's listing",
  "models.treatLikeTitle": "treated like {like}",
  "models.treatAs": "treat like",
  "models.pickScored": "pick a scored rung",
  "models.legend":
    "✓ usable rung. ≈ treated like a scored rung. ? unscored (click to map it). $n: cost tier.",
  "diag.openLogs": "Open logs folder",
  "diag.logsHelp":
    "catherd keeps 7 days of logs with secrets redacted. CatHouse's own log is in the Output panel (CatHouse).",
  "diag.lock": "Run a heavy command behind catherd's lock",
  "diag.lockHelp":
    "Runs the command in a terminal through `catherd lock`, sharing the machine-wide slots with running roles.",
  "diag.runLocked": "Run in terminal",
  "setup.checking": "Checking your machine…",
  "setup.checkingShort": "Checking…",
  "setup.recheck": "Re-check",
  "setup.copy": "Copy",
  "setup.running": "Running…",
  "session.blocked": "Tasks can't start yet: {reason}",
  "session.orchestratorRole": "orchestrator",
  "session.roleOf": "catherd role: {role}",
  "session.liveRoles": "Roles working now",
  "session.profileHint": "Profile {name} routes this repo’s roles",
  "session.modelHint": "The orchestrator runs on {model}",
  "session.more": "More chat actions",
  "session.working": "catherd is working…",
  "session.welcome": "What should catherd build?",
  "session.resumeLink": "or resume this repo’s saved run",
  "workspace.locked": "Stop the session to change repositories.",
  "runs.summary": "{n} runs",
  "runs.newTask": "New task",
  "runs.cancelNamed": "Cancel {name}",
  "runs.details": "Routing, history and state",
  "runs.agentRuns": "{n} Claude sub-agent runs",
  "runs.stat.roleRuns": "Role runs ok",
  "runs.stat.tokens": "Tokens in / out",
  "runs.stat.cost": "Cost",
  "runs.stat.minutes": "Minutes",
  "runs.stat.landed": "Landed",
  "setup.readyTitle": "Ready to go",
  "setup.toFixTitle": "{n} to fix before you start",
  "setup.checkedAgo": "checked {ago}",
  "setup.toFix": "Needs your click",
  "setup.recommended": "Recommended",
  "setup.allChecks": "Other checks ({n})",
  "setup.tools": "Logs and tools",
  "setup.copied": "Copied",
  "profiles.more": "Profile actions",
  "profiles.newFrom": "New profile from {name}",
  "profiles.pinToRepo": "Use only for this repo",
  "profiles.unpin": "use the active profile here",
  "profiles.deleteNamed": "Delete {name}",
  "profiles.inUse": "Active · this repo runs on it. Changes save automatically.",
  "profiles.pinnedHere": "This repo is pinned to it. Changes save automatically.",
  "profiles.activeButPinned": "Active everywhere, but this repo is pinned to {name}",
  "profiles.notInUse": "Not in use here",
  "profiles.autoSaved": "Profile saved",
  "profiles.refusedShort": "catherd refused that change; it was undone.",
  "profiles.conflictShort": "The profile changed outside CatHouse; reloaded.",
  "profiles.status.saving": "Saving…",
  "profiles.status.saved": "Saved",
  "profiles.status.error": "Not saved",
  "profiles.enableRole": "Use the {role} role",
  "profiles.noModels": "no model yet",
  "profiles.enforcementHint": "Whether catherd can enforce this role’s access level on its backend",
  "profiles.ladder": "Model ladder (catherd climbs it in order)",
  "profiles.startsHere": "start",
  "profiles.removeRung": "Remove {rung}",
  "profiles.addModel": "Add model",
  "profiles.searchModels": "Search models…",
  "profiles.objective.cost": "Lower cost",
  "profiles.objective.speed": "Faster",
  "profiles.jevHint": "Learn routing from run history",
  "profiles.budget.minutes": "Minutes",
  "profiles.budget.tokens": "Tokens",
  "profiles.budget.usd": "US dollars",
  "profiles.idleMin": "Idle timeout (min)",
  "profiles.wallMin": "Wall-clock limit (min)",
  "profiles.heavyHint": "Parallel heavy commands; empty = half the CPUs",
  "profiles.billingFor": "Billing for {backend}",
  "profiles.isolateBackend": "Isolate {backend}",
  "profiles.notify.milestone": "A milestone lands",
  "profiles.notify.finish": "A run finishes",
  "profiles.notify.blocked": "A run is blocked",
  "profiles.removeFailover": "Remove the stand-in for {from}",
  "profiles.addFailover": "Add a stand-in",
  "prompt.question.title": "The orchestrator asks",
  "prompt.question.other": "Other (type your own answer)",
  "prompt.question.submit": "Answer",
  "prompt.permission.title": "Allow {tool}?",
  "prompt.permission.message": "Optional note for Claude (sent when you deny)",
  "prompt.permission.allow": "Allow once",
  "prompt.permission.always": "Always allow",
  "prompt.permission.deny": "Deny",
} as const;

export type StringKey = keyof typeof en;

export function t(key: StringKey, vars: Record<string, string | number> = {}): string {
  return en[key].replace(/\{(\w+)\}/g, (_, name: string) => String(vars[name] ?? `{${name}}`));
}
