// User-facing strings live here (ADR 0004). Replace with @vscode/l10n bundles when a second
// locale is added; call sites keep using t().
const en = {
  "session.title": "Orchestrator",
  "session.taskLabel": "Task for catherd",
  "session.taskPlaceholder":
    "Describe what catherd should build. It plans, dispatches roles and reports back.",
  "session.roleGuide":
    "You are talking to the catherd orchestrator. It chooses and dispatches roles automatically; ask for a researcher or reviewer in your task when you want to steer the approach.",
  "session.start": "Start task",
  "session.resume": "Resume saved run",
  "session.interrupt": "Interrupt",
  "session.jumpLatest": "Latest",
  "session.stop": "Stop session",
  "session.new": "New chat",
  "session.newConfirm": "Stop and start new?",
  "session.followUp": "Message the orchestrator…",
  "session.send": "Send",
  "session.attach": "Attach files",
  "session.attachHelp":
    "Attached files are passed to the orchestrator with your message. Drag files onto the input (hold Shift when dragging from VS Code or Finder), or use Attach files.",
  "session.dropHere": "Drop files to attach",
  "session.removeAttachment": "Remove {name}",
  "session.attachments": "Attached files",
  "session.attachTooLarge":
    "{name} can't be attached: drop it from the VS Code Explorer (hold Shift) or use Attach files so its path is sent instead.",
  "session.pendingPrompts": "Pending requests from the orchestrator",
  "session.transcript": "Session transcript",
  "session.runStarted": "catherd run {run} started",
  "session.turnEnded": "turn ended: {subtype} · {cost}",
  "session.you": "You",
  "session.orchestrator": "catherd",
  "session.subagent": "Sub-agent",
  "session.steps": "{n} steps",
  "session.stepsRunning": "{n} running",
  "session.showEarlier": "Show {n} earlier steps",
  "session.input": "Input",
  "session.output": "Output",
  "session.runStartedTitle": "Run started",
  "session.turnDone": "Turn complete",
  "session.turnFailed": "Turn ended: {subtype}",
  "settings.open": "CatHouse settings",
  "settings.title": "Settings",
  "settings.fontSize": "Text size",
  "settings.smaller": "Smaller text",
  "settings.larger": "Larger text",
  "settings.presets": "Text size presets",
  "settings.fontSizeHelp": "Scales CatHouse relative to your VS Code font size.",
  "settings.preview": "The quick brown fox · Aa 123",
  "settings.apply": "Apply",
  "settings.cancel": "Cancel",
  "app.repo": "Repository:",
  "app.noFolder": "Open a folder (a git repository) to run tasks and see its runs.",
  "workspace.title": "Workspace repositories",
  "workspace.repo": "Repository for this chat",
  "workspace.none": "No repository selected",
  "workspace.add": "Add folders…",
  "workspace.current": "in use",
  "workspace.chatRepo": "Repository",
  "workspace.remove": "Remove current",
  "workspace.removeNamed": "Remove {name} from workspace",
  "workspace.removeHint": "Remove from this VS Code workspace (files stay on disk)",
  "workspace.removeConfirm": "Remove from workspace?",
  "workspace.help":
    "Choose one or more repository folders. Removing a folder only removes it from this VS Code workspace; files stay on disk.",
  "workspace.required": "Choose or add a repository before starting a task.",
  "runs.continue": "Continue in orchestrator",
  "runs.continueHelp":
    "Resume this repo's saved orchestrator session (or start one that resumes the latest run).",
  "session.mode": "Permissions:",
  "session.modeHelp":
    "catherd's own tools are always allowed; this sets how other tool calls are handled.",
  "session.mode.default": "ask (your Claude settings)",
  "session.mode.acceptEdits": "auto-accept file edits",
  "session.mode.plan": "plan only",
  "session.mode.auto": "auto (classifier)",
  "session.compacted":
    "The conversation was compacted. catherd runs can lose track of their protocol after this; check that routing, the reviewer and the verifier still run.",
  "tabs.setup": "Setup",
  "tabs.session": "Chat",
  "tabs.overview": "Overview",
  "tabs.runs": "Runs",
  "tabs.repos": "Repos",
  "tabs.profiles": "Profiles",
  "tabs.models": "Models",
  "tabs.diagnostics": "Diagnostics",
  "tabs.label": "CatHouse dashboard",
  "status.failed": "setup needs attention",
  "status.working": "agents working",
  "status.good": "ready",
  "common.info": "More information",
  "common.refresh": "Refresh",
  "common.loading": "Loading…",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "time.secs": "{n}s ago",
  "time.mins": "{n} min ago",
  "time.hours": "{n} h ago",
  "time.days": "{n} d ago",
  "runs.live": "{n} live",
  "runs.idle": "idle",
  "runs.roleRuns": "{n} role runs",
  "runs.landed": "{n} landed",
  "runs.budget": "budget {pct}%",
  "runs.paused": "Runs (updates paused)",
  "runs.updated": "updated {ago}",
  "runs.pause": "Pause updates",
  "runs.resume": "Resume updates",
  "runs.corrupt": "{n} run folders could not be read (see Diagnostics).",
  "runs.empty": "No runs yet. Start one from the Orchestrator tab.",
  "runs.back": "Runs",
  "runs.started": "started {ago}",
  "runs.budgetTitle": "Budget",
  "runs.totals": "Totals",
  "runs.totalsLine":
    "{runs} role runs · {ok} ok · {input}k in / {output}k out tokens · {cost} · {agents} Claude subagent runs · {minutes} min",
  "runs.jevLine": "Jev: {decisions} decisions, {fallbacks} fell back",
  "runs.liveTitle": "Live",
  "runs.noLive": "No role is running.",
  "runs.cancel": "Cancel role",
  "runs.cancelConfirm": "Click again to cancel",
  "runs.cancelled": "{name}: {status}",
  "runs.climbsTitle": "Climbs",
  "runs.environment": "(environment)",
  "runs.routesTitle": "Routes",
  "runs.noRoutes": "No lane has been routed yet.",
  "runs.col.lane": "Lane",
  "runs.col.role": "Role",
  "runs.col.source": "Decided by",
  "runs.col.kind": "Kind/difficulty",
  "runs.col.rung": "Rung",
  "runs.landedTitle": "Landed",
  "runs.noLanded": "No milestone has landed yet.",
  "runs.recordsTitle": "Role runs",
  "runs.noRecords": "No role has finished yet.",
  "runs.violations": "{n} files outside its lane",
  "runs.violationFiles": "Wrote outside its lane: {files}",
  "runs.tokensLine": "{input}k in / {output}k out tokens",
  "runs.changed": "changed {files}",
  "runs.debug": "Debug (exit, stderr, events)",
  "runs.noExit": "no exit.json",
  "runs.stateTitle": "state.md",
  "runs.warningsTitle": "Warnings",
  "overview.setup": "Setup",
  "overview.issues": "{n} to fix",
  "overview.profile": "Profile",
  "overview.runCount": "{n} runs",
  "overview.profileCount": "{n} profiles",
  "overview.recentRuns": "Recent runs",
  "overview.newTask": "New task",
  "profiles.active": "active",
  "profiles.thisRepo": "this repo",
  "profiles.invalid": "invalid",
  "profiles.profile": "Profile",
  "profiles.discardConfirm": "Discard unsaved changes?",
  "profiles.discardDetail": "This reloads the profile and removes every staged edit.",
  "profiles.activateTitle": "Change the active profile?",
  "profiles.activateGlobal": "Make {name} the global active profile.",
  "profiles.activateRepo": "Use {name} for this repository only.",
  "profiles.activateDirty": "Unsaved edits are not included.",
  "profiles.confirm": "Confirm",
  "profiles.filter": "Filter profile settings",
  "profiles.filterHelp": "Searches section paths, labels and current values. Press / to focus.",
  "profiles.noFilterResults": "No profile setting matches this filter.",
  "profiles.help.roles":
    "catherd 1.0.0 defines these eight roles. Configure whether they run, their access, ordered model ladder and starting rung; custom roles are not supported.",
  "profiles.help.routing":
    "Prefer lower cost or higher speed; Jev can refine routing from run history.",
  "profiles.help.billing": "Tell catherd which quota or billing pool each backend consumes.",
  "profiles.help.harness": "Isolated harnesses avoid loading your personal backend configuration.",
  "profiles.help.budget": "Soft caps guide the orchestrator; an empty value means no cap.",
  "profiles.help.failover": "Choose a stand-in from a different quota when a rung is unavailable.",
  "profiles.help.timeouts":
    "Limit idle and wall time, preflight confirmation and heavy-work slots.",
  "profiles.help.notify": "Choose which run events produce notifications.",
  "profiles.unsaved": "{n} unsaved",
  "profiles.makeActive": "Make active",
  "profiles.useForRepo": "Use for this repo",
  "profiles.unbind": "Unbind this repo",
  "profiles.activated": "{name} is now the active profile.",
  "profiles.bound": "This repo now runs on {name}.",
  "profiles.unbound": "This repo runs on the active profile again.",
  "profiles.new": "New profile…",
  "profiles.newTitle": "Create a profile",
  "profiles.name": "Profile name",
  "profiles.create": "Create",
  "profiles.creating": "Creating…",
  "profiles.badName": "Profile names use lowercase letters, digits and dashes (max 32).",
  "profiles.exists": "A profile named {name} already exists.",
  "profiles.created": "Created {name}.",
  "profiles.delete": "Delete",
  "profiles.deleteConfirm": "Click again to delete",
  "profiles.removed": "Deleted {name}.",
  "profiles.boundTo": "Bound to: {repos}",
  "profiles.undo": "Undo",
  "profiles.redo": "Redo",
  "profiles.discard": "Discard",
  "profiles.save": "Save…",
  "profiles.saved": "Saved ({n} changes).",
  "profiles.nowActive": "now active",
  "profiles.newSession": "Start a new orchestrator session to use: {agents}",
  "profiles.appliesWhen":
    "Applies to: native Claude agents in new sessions; codex, claude-code and opencode from the next dispatch.",
  "profiles.refused": "catherd refused the change; nothing was written:",
  "profiles.conflict":
    "The profile changed on disk since you opened it. Reload it and redo your edits.",
  "profiles.reload": "Reload profile",
  "profiles.unchanged": "Nothing to save.",
  "profiles.previewTitle": "Save these changes?",
  "profiles.treatLikeLine": "treat {rung} like {like}",
  "profiles.saveActivate": "Save & make active",
  "profiles.saveRepo": "Save & use for this repo",
  "profiles.roles": "Roles",
  "profiles.access": "Access for {role}",
  "profiles.defaultRung": "start on",
  "profiles.cheapest": "the cheapest that clears the bar",
  "profiles.up": "Move up",
  "profiles.down": "Move down",
  "profiles.remove": "Remove",
  "profiles.addRung": "Add a rung to {role}",
  "profiles.addRungPlaceholder": "+ add rung…",
  "profiles.unscored": "unscored, needs treat-like",
  "profiles.treatPrompt": "{rung} is unscored. Treat it like:",
  "profiles.addWithTreat": "Add",
  "profiles.routing": "Routing",
  "profiles.objective": "Objective",
  "profiles.jev": "Jev",
  "profiles.billing": "Billing",
  "profiles.harness": "Harness isolation",
  "profiles.isolated": "isolated",
  "profiles.ownConfig": "your own config",
  "profiles.budget": "Budget (soft cap)",
  "profiles.noCap": "no cap",
  "profiles.failover": "Failover",
  "profiles.inferred": "inferred",
  "profiles.failoverFrom": "when this rung hits a limit…",
  "profiles.failoverTo": "…stand in with",
  "profiles.add": "Add",
  "profiles.timeouts": "Timeouts & limits",
  "profiles.preflightConfirm": "Show preflight commands before running them",
  "profiles.heavy": "heavy slots",
  "profiles.notify": "Push notifications",
  "profiles.expandAll": "Expand all",
  "profiles.collapseAll": "Collapse all",
  "profiles.toggleRungs": "Show or hide rungs for {role}",
  "profiles.summary.roles": "{n}/{total} enabled",
  "profiles.summary.rungs": "{n} rungs",
  "profiles.summary.harness": "{n}/{total} isolated",
  "profiles.summary.failover": "{n} stand-ins",
  "profiles.summary.timeouts": "idle {idle} min · wall {wall} min",
  "profiles.summary.none": "none",
  "models.title": "Models ({n})",
  "models.refresh": "Refresh catalog",
  "models.refreshing": "Refreshing model listings…",
  "models.count": "{n} models",
  "models.treated": "{rung} is now treated like {like}.",
  "models.role": "Role",
  "models.anyRole": "any role",
  "models.backend": "Backend",
  "models.anyBackend": "any backend",
  "models.search": "Search models",
  "models.scoredOnly": "scored only",
  "models.none": "No model matches.",
  "models.notListed": "not in your account's listing",
  "models.treatLikeTitle": "treated like {like}",
  "models.treatAs": "treat like",
  "models.pickScored": "pick a scored rung",
  "models.legend":
    "✓ usable rung. ≈ treated like a scored rung. ? unscored (click to map it). $n: cost tier.",
  "diag.doctor": "catherd doctor (checked {ago})",
  "diag.never": "never",
  "diag.runDoctor": "Run doctor",
  "diag.logs": "Logs",
  "diag.openLogs": "Open logs folder",
  "diag.logsHelp":
    "catherd keeps 7 days of logs with secrets redacted. CatHouse's own log is in the Output panel (CatHouse).",
  "diag.lock": "Run a heavy command behind catherd's lock",
  "diag.lockHelp":
    "Runs the command in a terminal through `catherd lock`, sharing the machine-wide slots with running roles.",
  "diag.runLocked": "Run in terminal",
  "setup.title": "Setup",
  "setup.checking": "Checking your machine…",
  "setup.checkingShort": "Checking…",
  "setup.recheck": "Re-check",
  "setup.ready": "ready",
  "setup.almost": "almost ready",
  "setup.required": "setup required",
  "setup.level.gate": "Required to use CatHouse",
  "setup.level.start": "Required to start tasks",
  "setup.level.optional": "Optional",
  "setup.copy": "Copy",
  "setup.running": "Running…",
  "setup.done": "{action} finished",
  "setup.output": "Output",
  "session.blocked": "Tasks can't start yet: {reason}",
  "prompt.question.title": "The orchestrator asks",
  "prompt.question.other": "Other (type your own answer)",
  "prompt.question.submit": "Answer",
  "prompt.permission.title": "Allow {tool}?",
  "prompt.permission.message": "Optional note for Claude (sent when you deny)",
  "prompt.permission.allow": "Allow once",
  "prompt.permission.always": "Always allow",
  "prompt.permission.deny": "Deny",
} as const;

export type StringKey = keyof typeof en;

export function t(key: StringKey, vars: Record<string, string | number> = {}): string {
  return en[key].replace(/\{(\w+)\}/g, (_, name: string) => String(vars[name] ?? `{${name}}`));
}
