// User-facing strings live here (ADR 0004). Replace with @vscode/l10n bundles when a second
// locale is added; call sites keep using t().
const en = {
  "app.title": "CatHouse",
  "app.tagline": "herds coding agents",
  "sidebar.openDashboard": "Open dashboard",
  "session.title": "Orchestrator",
  "session.taskLabel": "Task for catherd",
  "session.taskPlaceholder":
    "Describe what catherd should build. It plans, dispatches roles and reports back.",
  "session.start": "Start task",
  "session.resume": "Resume saved run",
  "session.interrupt": "Interrupt",
  "session.stop": "Stop session",
  "session.followUp": "Message the orchestrator…",
  "session.send": "Send",
  "session.transcript": "Session transcript",
  "session.runStarted": "catherd run {run} started",
  "session.turnEnded": "turn ended: {subtype} · {cost}",
  "sidebar.phase": "Session: {phase}",
  "sidebar.setupRequired": "Setup needed before CatHouse can run catherd.",
  "sidebar.openSetup": "Open Setup",
  "app.repo": "Repository:",
  "app.noFolder": "Open a folder (a git repository) to run tasks and see its runs.",
  "runs.continue": "Continue in orchestrator",
  "runs.continueHelp":
    "Resume this repo's saved orchestrator session (or start one that resumes the latest run).",
  "session.mode": "Permissions:",
  "session.modeHelp":
    "catherd's own tools are always allowed; this sets how other tool calls are handled.",
  "session.mode.default": "ask (your Claude settings)",
  "session.mode.acceptEdits": "auto-accept file edits",
  "session.mode.plan": "plan only",
  "session.mode.auto": "auto (classifier)",
  "session.compacted":
    "The conversation was compacted. catherd runs can lose track of their protocol after this; check that routing, the reviewer and the verifier still run.",
  "tabs.setup": "Setup",
  "tabs.session": "Orchestrator",
  "tabs.overview": "Overview",
  "tabs.runs": "Runs",
  "tabs.profiles": "Profiles",
  "tabs.models": "Models",
  "tabs.diagnostics": "Diagnostics",
  "common.refresh": "Refresh",
  "common.loading": "Loading…",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "time.secs": "{n}s ago",
  "time.mins": "{n} min ago",
  "time.hours": "{n} h ago",
  "time.days": "{n} d ago",
  "runs.live": "{n} live",
  "runs.idle": "idle",
  "runs.roleRuns": "{n} role runs",
  "runs.landed": "{n} landed",
  "runs.budget": "budget {pct}%",
  "runs.paused": "Runs (updates paused)",
  "runs.updated": "updated {ago}",
  "runs.pause": "Pause updates",
  "runs.resume": "Resume updates",
  "runs.corrupt": "{n} run folders could not be read (see Diagnostics).",
  "runs.empty": "No runs yet. Start one from the Orchestrator tab.",
  "runs.back": "Runs",
  "runs.started": "started {ago}",
  "runs.budgetTitle": "Budget",
  "runs.totals": "Totals",
  "runs.totalsLine":
    "{runs} role runs · {ok} ok · {input}k in / {output}k out tokens · {cost} · {agents} Claude subagent runs · {minutes} min",
  "runs.jevLine": "Jev: {decisions} decisions, {fallbacks} fell back",
  "runs.liveTitle": "Live",
  "runs.noLive": "No role is running.",
  "runs.cancel": "Cancel role",
  "runs.cancelConfirm": "Click again to cancel",
  "runs.cancelled": "{name}: {status}",
  "runs.climbsTitle": "Climbs",
  "runs.environment": "(environment)",
  "runs.routesTitle": "Routes",
  "runs.noRoutes": "No lane has been routed yet.",
  "runs.col.lane": "Lane",
  "runs.col.role": "Role",
  "runs.col.source": "Decided by",
  "runs.col.kind": "Kind/difficulty",
  "runs.col.rung": "Rung",
  "runs.landedTitle": "Landed",
  "runs.noLanded": "No milestone has landed yet.",
  "runs.recordsTitle": "Role runs",
  "runs.noRecords": "No role has finished yet.",
  "runs.violations": "{n} files outside its lane",
  "runs.violationFiles": "Wrote outside its lane: {files}",
  "runs.tokensLine": "{input}k in / {output}k out tokens",
  "runs.changed": "changed {files}",
  "runs.debug": "Debug (exit, stderr, events)",
  "runs.noExit": "no exit.json",
  "runs.stateTitle": "state.md",
  "runs.warningsTitle": "Warnings",
  "overview.setup": "Setup",
  "overview.openSetup": "Open Setup",
  "overview.readyLine": "catherd is installed, set up and ready.",
  "overview.profile": "Profile",
  "overview.openProfiles": "Edit profiles",
  "overview.profileCount": "{n} profiles",
  "overview.recentRuns": "Recent runs",
  "overview.newTask": "New task",
  "profiles.active": "active",
  "profiles.thisRepo": "this repo",
  "profiles.invalid": "invalid",
  "profiles.profile": "Profile",
  "profiles.discardConfirm": "Discard unsaved changes?",
  "profiles.unsaved": "{n} unsaved",
  "profiles.makeActive": "Make active",
  "profiles.useForRepo": "Use for this repo",
  "profiles.unbind": "Unbind this repo",
  "profiles.activated": "{name} is now the active profile.",
  "profiles.bound": "This repo now runs on {name}.",
  "profiles.unbound": "This repo runs on the active profile again.",
  "profiles.new": "New profile…",
  "profiles.newPrompt": "Name for the new profile (a copy of this one):",
  "profiles.badName": "Profile names use lowercase letters, digits and dashes (max 32).",
  "profiles.exists": "A profile named {name} already exists.",
  "profiles.created": "Created {name}.",
  "profiles.delete": "Delete",
  "profiles.deleteConfirm": "Click again to delete",
  "profiles.removed": "Deleted {name}.",
  "profiles.boundTo": "Bound to: {repos}",
  "profiles.undo": "Undo",
  "profiles.redo": "Redo",
  "profiles.discard": "Discard",
  "profiles.save": "Save…",
  "profiles.saved": "Saved ({n} changes).",
  "profiles.nowActive": "now active",
  "profiles.newSession": "Start a new orchestrator session to use: {agents}",
  "profiles.appliesWhen":
    "Applies to: native Claude agents in new sessions; codex, claude-code and opencode from the next dispatch.",
  "profiles.refused": "catherd refused the change; nothing was written:",
  "profiles.conflict":
    "The profile changed on disk since you opened it. Reload it and redo your edits.",
  "profiles.reload": "Reload profile",
  "profiles.unchanged": "Nothing to save.",
  "profiles.previewTitle": "Save these changes?",
  "profiles.treatLikeLine": "treat {rung} like {like}",
  "profiles.saveActivate": "Save & make active",
  "profiles.saveRepo": "Save & use for this repo",
  "profiles.roles": "Roles",
  "profiles.access": "Access for {role}",
  "profiles.defaultRung": "start on",
  "profiles.cheapest": "the cheapest that clears the bar",
  "profiles.up": "Move up",
  "profiles.down": "Move down",
  "profiles.remove": "Remove",
  "profiles.addRung": "Add a rung to {role}",
  "profiles.addRungPlaceholder": "+ add rung…",
  "profiles.unscored": "unscored, needs treat-like",
  "profiles.treatPrompt": "{rung} is unscored. Treat it like:",
  "profiles.addWithTreat": "Add",
  "profiles.routing": "Routing",
  "profiles.objective": "Objective",
  "profiles.jev": "Jev",
  "profiles.billing": "Billing",
  "profiles.harness": "Harness isolation",
  "profiles.isolated": "isolated",
  "profiles.ownConfig": "your own config",
  "profiles.budget": "Budget (soft cap)",
  "profiles.noCap": "no cap",
  "profiles.failover": "Failover",
  "profiles.inferred": "inferred",
  "profiles.failoverFrom": "when this rung hits a limit…",
  "profiles.failoverTo": "…stand in with",
  "profiles.add": "Add",
  "profiles.timeouts": "Timeouts & limits",
  "profiles.preflightConfirm": "Show preflight commands before running them",
  "profiles.heavy": "heavy slots",
  "profiles.notify": "Push notifications",
  "models.title": "Models ({n})",
  "models.refresh": "Refresh catalog",
  "models.refreshing": "Refreshing model listings…",
  "models.count": "{n} models",
  "models.treated": "{rung} is now treated like {like}.",
  "models.role": "Role",
  "models.anyRole": "any role",
  "models.backend": "Backend",
  "models.anyBackend": "any backend",
  "models.search": "Search models",
  "models.scoredOnly": "scored only",
  "models.none": "No model matches.",
  "models.notListed": "not in your account's listing",
  "models.treatLikeTitle": "treated like {like}",
  "models.treatAs": "treat like",
  "models.pickScored": "pick a scored rung",
  "models.legend":
    "Green: usable rung. ≈ treated like a scored rung. ? unscored (click to map it). $n: cost tier.",
  "diag.doctor": "catherd doctor (checked {ago})",
  "diag.never": "never",
  "diag.runDoctor": "Run doctor",
  "diag.logs": "Logs",
  "diag.openLogs": "Open logs folder",
  "diag.logsHelp":
    "catherd keeps 7 days of logs with secrets redacted. CatHouse's own log is in the Output panel (CatHouse).",
  "diag.lock": "Run a heavy command behind catherd's lock",
  "diag.lockHelp":
    "Runs the command in a terminal through `catherd lock`, sharing the machine-wide slots with running roles.",
  "diag.runLocked": "Run in terminal",
  "setup.title": "Setup",
  "setup.checking": "Checking your machine…",
  "setup.checkingShort": "Checking…",
  "setup.recheck": "Re-check",
  "setup.ready": "ready",
  "setup.almost": "almost ready",
  "setup.required": "setup required",
  "setup.level.gate": "Required to use CatHouse",
  "setup.level.start": "Required to start tasks",
  "setup.level.optional": "Optional",
  "setup.copy": "Copy",
  "setup.running": "Running…",
  "setup.done": "{action} finished",
  "setup.output": "Output",
  "session.blocked": "Tasks can't start yet: {reason}",
  "sidebar.pending": "{count} waiting for you",
  "prompt.question.title": "The orchestrator asks",
  "prompt.question.other": "Other (type your own answer)",
  "prompt.question.submit": "Answer",
  "prompt.permission.title": "Allow {tool}?",
  "prompt.permission.message": "Optional note for Claude (sent when you deny)",
  "prompt.permission.allow": "Allow once",
  "prompt.permission.always": "Always allow",
  "prompt.permission.deny": "Deny",
} as const;

export type StringKey = keyof typeof en;

export function t(key: StringKey, vars: Record<string, string | number> = {}): string {
  return en[key].replace(/\{(\w+)\}/g, (_, name: string) => String(vars[name] ?? `{${name}}`));
}
