export const PREFIXES = ["session.", "chat."] as const;

export const STRINGS = {
  "session.taskPlaceholder": "Describe a task for catherd…",
  "session.roleGuide":
    "catherd plans the work, sends each part to the right role and model, and reports back. Ask for a researcher or reviewer in your task to steer it.",
  "session.start": "Start task",
  "session.resume": "Resume saved run",
  "session.interrupt": "Interrupt",
  "session.jumpLatest": "Latest",
  "session.stop": "Stop session",
  "session.new": "New chat",
  "session.newConfirm": "Stop and start new?",
  "session.followUp": "Message the orchestrator…",
  "session.send": "Send",
  "session.attach": "Attach files",
  "session.dropHere": "Drop files to attach",
  "session.removeAttachment": "Remove {name}",
  "session.attachments": "Attached files",
  "session.attachTooLarge":
    "{name} can't be attached: drop it from the VS Code Explorer (hold Shift) or use Attach files so its path is sent instead.",
  "session.pendingPrompts": "Pending requests from the orchestrator",
  "session.transcript": "Session transcript",
  "session.you": "You",
  "session.orchestrator": "catherd",
  "session.steps": "{n} steps",
  "session.stepsRunning": "{n} running",
  "session.showEarlier": "Show {n} earlier steps",
  "session.input": "Input",
  "session.output": "Output",
  "session.runStartedTitle": "Run started",
  "session.turnDone": "Turn complete",
  "session.turnFailed": "Turn ended: {subtype}",
  "session.switchToCodex": "Switch to Codex",
  "session.switchToCodexHint":
    "Ends this Claude chat. New tasks use Codex after its Setup checks pass; this chat stays with Claude.",
  "session.mode": "Permissions",
  "session.modeHelp":
    "catherd's own tools are always allowed; this sets how other tool calls are handled.",
  "session.mode.default": "ask (your Claude settings)",
  "session.mode.acceptEdits": "auto-accept file edits",
  "session.mode.plan": "plan only",
  "session.mode.auto": "auto (classifier)",
  "session.inbound": "catherd reported back",
  "session.compacted":
    "The conversation was compacted. catherd runs can lose track of their protocol after this; check that routing, the reviewer and the verifier still run.",
  "session.blocked": "Tasks can't start yet: {reason}",
  "session.orchestratorRole": "orchestrator",
  "session.roleOf": "catherd role: {role}",
  "session.liveRoles": "Roles working now",
  "session.profileHint": "Profile {name} routes this repo’s roles",
  "session.modelHint": "The orchestrator runs on {model}",
  "session.more": "More chat actions",
  "session.working": "catherd is working…",
  "session.welcome": "What should catherd build?",
  "session.resumeLink": "or resume this repo’s saved run",
} as const;
