export const PREFIXES = ["profiles."] as const;

export const STRINGS = {
  "profiles.active": "active",
  "profiles.thisRepo": "this repo",
  "profiles.profile": "Profile",
  "profiles.help.routing":
    "Prefer lower cost or higher speed; Jev can refine routing from run history.",
  "profiles.help.billing": "Tell catherd which quota or billing pool each backend consumes.",
  "profiles.help.harness": "Isolated harnesses avoid loading your personal backend configuration.",
  "profiles.help.budget": "Soft caps guide the orchestrator; an empty value means no cap.",
  "profiles.help.failover": "Choose a stand-in from a different quota when a rung is unavailable.",
  "profiles.help.timeouts":
    "Limit idle and wall time, preflight confirmation and heavy-work slots.",
  "profiles.help.notify": "Choose which run events produce notifications.",
  "profiles.unbind": "Unbind this repo",
  "profiles.activated": "{name} is now the active profile.",
  "profiles.bound": "This repo now runs on {name}.",
  "profiles.unbound": "This repo runs on the active profile again.",
  "profiles.name": "Profile name",
  "profiles.create": "Create",
  "profiles.creating": "Creating…",
  "profiles.badName": "Profile names use lowercase letters, digits and dashes (max 32).",
  "profiles.exists": "A profile named {name} already exists.",
  "profiles.created": "Created {name}.",
  "profiles.deleteConfirm": "Click again to delete",
  "profiles.removed": "Deleted {name}.",
  "profiles.boundTo": "Bound to: {repos}",
  "profiles.undo": "Undo",
  "profiles.save": "Save…",
  "profiles.newSession": "Start a new orchestrator session to use: {agents}",
  "profiles.appliesWhen":
    "Applies to: native Claude agents in new sessions; codex, claude-code, opencode, cursor, grok and antigravity from the next dispatch.",
  "profiles.roles": "Roles",
  "profiles.access": "Access for {role}",
  "profiles.defaultRung": "start on",
  "profiles.cheapest": "the cheapest that clears the bar",
  "profiles.up": "Move up",
  "profiles.down": "Move down",
  "profiles.remove": "Remove",
  "profiles.addRung": "Add a rung to {role}",
  "profiles.unscored": "unscored: catherd infers its values",
  "profiles.treatPrompt":
    "{rung} is unscored. catherd will borrow its nearest stand-in's values; you can pick one:",
  "profiles.addWithTreat": "Add",
  "profiles.addInferred": "Add (let catherd infer)",
  "profiles.routing": "Routing",
  "profiles.objective": "Objective",
  "profiles.jev": "Jev",
  "profiles.billing": "Billing",
  "profiles.harness": "Harness isolation",
  "profiles.isolated": "isolated",
  "profiles.ownConfig": "your own config",
  "profiles.budget": "Budget (soft cap)",
  "profiles.noCap": "no cap",
  "profiles.failover": "Failover",
  "profiles.inferred": "inferred",
  "profiles.failoverFrom": "when this rung hits a limit…",
  "profiles.failoverTo": "…stand in with",
  "profiles.add": "Add",
  "profiles.timeouts": "Limits",
  "profiles.preflightConfirm": "Show preflight commands before running them",
  "profiles.heavy": "Heavy-work slots",
  "profiles.notify": "Notify me when",
  "profiles.summary.roles": "{n}/{total} enabled",
  "profiles.more": "Profile actions",
  "profiles.newFrom": "New profile from {name}",
  "profiles.pinToRepo": "Use only for this repo",
  "profiles.unpin": "use the active profile here",
  "profiles.deleteNamed": "Delete {name}",
  "profiles.inUse": "Active · this repo runs on it. Changes save automatically.",
  "profiles.pinnedHere": "This repo is pinned to it. Changes save automatically.",
  "profiles.activeButPinned": "Active everywhere, but this repo is pinned to {name}",
  "profiles.notInUse": "Not in use here",
  "profiles.autoSaved": "Profile saved",
  "profiles.refusedShort": "catherd refused that change; it was undone.",
  "profiles.conflictShort": "The profile changed outside CatHouse; reloaded.",
  "profiles.status.saving": "Saving…",
  "profiles.status.saved": "Saved",
  "profiles.status.error": "Not saved",
  "profiles.enableRole": "Use the {role} role",
  "profiles.noModels": "no model yet",
  "profiles.enforcementHint": "Whether catherd can enforce this role’s access level on its backend",
  "profiles.ladder": "Model ladder (catherd climbs it in order)",
  "profiles.startsHere": "start",
  "profiles.removeRung": "Remove {rung}",
  "profiles.addModel": "Add model",
  "profiles.searchModels": "Search models…",
  "profiles.objective.cost": "Lower cost",
  "profiles.objective.speed": "Faster",
  "profiles.jevHint": "Learn routing from run history",
  "profiles.budget.minutes": "Minutes",
  "profiles.budget.tokens": "Tokens",
  "profiles.budget.usd": "US dollars",
  "profiles.idleMin": "Idle timeout (min)",
  "profiles.wallMin": "Wall-clock limit (min)",
  "profiles.heavyHint": "Parallel heavy commands; empty = half the CPUs",
  "profiles.billingFor": "Billing for {backend}",
  "profiles.isolateBackend": "Isolate {backend}",
  "profiles.notify.milestone": "A milestone lands",
  "profiles.notify.finish": "A run finishes",
  "profiles.notify.blocked": "A run is blocked",
  "profiles.removeFailover": "Remove the stand-in for {from}",
  "profiles.addFailover": "Add a stand-in",
} as const;
