export const PREFIXES = ["runs.", "overview."] as const;

export const STRINGS = {
  "runs.continue": "Continue in chat",
  "runs.continueHelp":
    "Resume this repo's saved orchestrator session (or start one that resumes the latest run).",
  "runs.live": "{n} live",
  "runs.roleRuns": "{n} role runs",
  "runs.landed": "{n} landed",
  "runs.budget": "budget {pct}%",
  "runs.session": "session {name}",
  "runs.sessionLive": "session {name} (live)",
  "runs.continuedIn": "continued in {name}",
  "runs.supersededBy": "superseded by {id}",
  "runs.waiting": "{n} results waiting for the orchestrator",
  "runs.waitingStalled": "stalled: {n} results waiting for the orchestrator",
  "runs.questionsTitle": "Parked questions",
  "runs.questionsHelp":
    "catherd parked these milestones for your answer; the other milestones go on. Answer in the orchestrator chat.",
  "runs.verifierStep": "Verifier: {item} ({ago})",
  "runs.verifierCarried": "Verifier: {item}, carried over ({ago})",
  "runs.corrupt": "{n} run folders could not be read (see Setup → Logs).",
  "runs.empty": "No runs yet. Start one from Chat.",
  "runs.back": "Runs",
  "runs.started": "started {ago}",
  "runs.budgetTitle": "Budget",
  "runs.jevLine": "Jev: {decisions} decisions, {fallbacks} fell back",
  "runs.liveTitle": "Live",
  "runs.cancelConfirm": "Click again to cancel",
  "runs.cancelled": "{name}: {status}",
  "runs.climbsTitle": "Climbs",
  "runs.environment": "(environment)",
  "runs.routesTitle": "Routes",
  "runs.noRoutes": "No lane has been routed yet.",
  "runs.landedTitle": "Landed",
  "runs.recordsTitle": "Role runs",
  "runs.noRecords": "No role has finished yet.",
  "runs.violations": "{n} files outside its lane",
  "runs.violationFiles": "Wrote outside its lane: {files}",
  "runs.tokensLine": "{input}k in / {output}k out tokens",
  "runs.changed": "changed {files}",
  "runs.debug": "Debug (exit, stderr, events)",
  "runs.noExit": "no exit.json",
  "runs.stateTitle": "state.md",
  "runs.summary": "{n} runs",
  "runs.newTask": "New task",
  "runs.cancelNamed": "Cancel {name}",
  "runs.details": "Routing, history and state",
  "runs.agentRuns": "{n} Claude sub-agent runs",
  "runs.stat.roleRuns": "Role runs ok",
  "runs.stat.tokens": "Tokens in / out",
  "runs.stat.cost": "Cost",
  "runs.stat.minutes": "Minutes",
  "runs.stat.landed": "Landed",
} as const;
